# Generated by Django 3.1.3 on 2022-01-16 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('time_data', models.DateTimeField(default=datetime.datetime(2022, 1, 16, 16, 4, 7, 558944, tzinfo=utc))),
            ],
        ),
    ]
