# Generated by Django 3.1.3 on 2022-01-16 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0002_auto_20220116_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 16, 13, 2, 197314, tzinfo=utc)),
        ),
    ]
