# Generated by Django 3.1.3 on 2022-01-16 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0003_auto_20220116_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_data',
        ),
        migrations.AddField(
            model_name='task',
            name='time_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 17, 29, 45, 809656, tzinfo=utc)),
        ),
    ]
